# wrangler.toml
name = "plataforma-musicas"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "service-worker"

[env.production]
name = "plataforma-musicas"
route = "djpools.nexorrecords.com.br/*"

[env.staging]
name = "plataforma-musicas-staging"
route = "staging.djpools.nexorrecords.com.br/*"

# Configurações para Next.js
[env.production.vars]
NODE_ENV = "production"

[env.staging.vars]
NODE_ENV = "staging"
